### Creating problem
POST {{server}}/api/v1/problems
Content-Type: application/json
Authorization: Bearer {{auth.token}}

{
  "title": "New problem",
  "topic": "Basic algorithms",
  "difficulty": "MEDIUM",
  "statement": "Statement is big enough",
  "execution_time_limit_ms": 1000,
  "execution_memory_limit_kb": 1024,
  "default_evaluation_type": "EXACT_MATCH"
}

### Updating problem
PATCH {{server}}/api/v1/problems/1
Content-Type: application/json
Authorization: Bearer {{auth.token}}

{
  "title": "New problem 2",
  "topic": "Basic algorithms",
  "difficulty": "HARD",
  "statement": "Statement is big enough 2",
  "execution_time_limit_ms": 2000,
  "execution_memory_limit_kb": 3072,
  "default_evaluation_type": "SCRIPT_CHECK"
}