-- Rename the old table
ALTER TABLE problem_topics RENAME TO old_problem_topics;

-- Create the new table with a surrogate ID key
CREATE TABLE problem_topics (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

-- Copy existing topics
INSERT INTO problem_topics (name)
SELECT name FROM old_problem_topics;

-- Add new foreign key column to problems
ALTER TABLE problems ADD COLUMN topic_id INT REFERENCES problem_topics(id) ON DELETE SET NULL;

-- Migrate relationships
UPDATE problems p
SET topic_id = pt.id
FROM problem_topics pt
WHERE p.topic = pt.name;

-- Drop the old constraint and column from problems
ALTER TABLE problems DROP CONSTRAINT problems_topic_fkey;
ALTER TABLE problems DROP COLUMN topic;

-- Drop the old table
DROP TABLE old_problem_topics;

-- Create an index for the new foreign key
CREATE INDEX idx_problems_topic_id ON problems (topic_id);
