CREATE TYPE "problem_difficulties" AS ENUM (
  'VERY_EASY',
  'EASY',
  'MEDIUM',
  'HARD',
  'VERY_HARD'
);
CREATE TYPE "evaluation_types" AS ENUM (
  'EXACT_MATCH',
  'SCRIPT_CHECK'
);
CREATE TYPE "solution_statuses" AS ENUM (
  'IN_QUEUE',
  'COMPILING',
  'COMPILATION_ERROR',
  'EXECUTION',
  'RUNTIME_ERROR',
  'SUCCESS',
  'TEST_FAILED',
  'TIME_LIMIT_EXCEEDED',
  'MEMORY_LIMIT_EXCEEDED',
  'OUTPUT_LIMIT_EXCEEDED',
  'INTERNAL_ERROR'
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" text NOT NULL,
  "last_name" text,
  "photo_url" text,
  "email" text UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "problems" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "topic" text,
  "difficulty" problem_difficulties NOT NULL,
  "statement" text NOT NULL,
  "execution_time_limit_ms" int NOT NULL CHECK ("execution_time_limit_ms" > 0),
  "execution_memory_limit_kb" int NOT NULL CHECK ("execution_memory_limit_kb" > 0),
  "default_evaluation_type" evaluation_types,
  "default_script_checker_id" int,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "tests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "problem_id" int,
  "ordinal" int NOT NULL CHECK ("ordinal" >= 0),
  "is_example" bool NOT NULL DEFAULT false,
  "input_data" text NOT NULL,
  "expected_output" text,
  "override_evaluation_type" evaluation_types,
  "override_script_checker_id" int,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("problem_id", "ordinal")
);
CREATE TABLE IF NOT EXISTS "script_checkers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "language_id" int NOT NULL,
  "code" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "solutions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "problem_id" int NOT NULL,
  "user_id" int NOT NULL,
  "code" text,
  "language_id" int NOT NULL,
  "status" solution_statuses NOT NULL DEFAULT 'IN_QUEUE',
  "test_case_reached" int,
  "execution_time_ms" int,
  "execution_memory_kb" int,
  "sent_at" timestamptz NOT NULL DEFAULT now(),
  "executed_at" timestamptz
);
CREATE TABLE IF NOT EXISTS "available_languages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "language" text NOT NULL,
  "version" text NOT NULL,
  UNIQUE ("language", "version")
);
CREATE TABLE IF NOT EXISTS "problem_topics" (
  "name" text PRIMARY KEY
);

CREATE INDEX ON "problems" ("topic");
CREATE INDEX ON "tests" ("problem_id");
CREATE INDEX ON "solutions" ("user_id");
CREATE INDEX ON "solutions" ("problem_id");
CREATE INDEX ON "solutions" ("status");

ALTER TABLE "problems" ADD FOREIGN KEY ("topic") REFERENCES "problem_topics" ("name") ON DELETE SET NULL;
ALTER TABLE "problems" ADD FOREIGN KEY ("default_script_checker_id") REFERENCES "script_checkers" ("id") ON DELETE SET NULL ;

ALTER TABLE "tests" ADD FOREIGN KEY ("problem_id") REFERENCES "problems" ("id") ON DELETE CASCADE;
ALTER TABLE "tests" ADD FOREIGN KEY ("override_script_checker_id") REFERENCES "script_checkers" ("id") ON DELETE SET NULL;

ALTER TABLE "script_checkers" ADD FOREIGN KEY ("language_id") REFERENCES "available_languages" ("id") ON DELETE CASCADE;

ALTER TABLE "solutions" ADD FOREIGN KEY ("problem_id") REFERENCES "problems" ("id") ON DELETE CASCADE;
ALTER TABLE "solutions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "solutions" ADD FOREIGN KEY ("language_id") REFERENCES "available_languages" ("id") ON DELETE CASCADE;
