CREATE TABLE IF NOT EXISTS "contests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "overview" text,
  "rules" text,
  "start_time" timestamptz NOT NULL,
  "freeze_time" timestamptz,
  "end_time" timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS "contest_problems" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contest_id" int NOT NULL,
  "problem_id" int NOT NULL,
  "ordinal" int NOT NULL,
  UNIQUE ("contest_id", "ordinal"),
  UNIQUE ("contest_id", "problem_id")
);

CREATE TABLE IF NOT EXISTS "contest_members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "contest_id" int NOT NULL,
  "result_points" int,
  "result_place" int,
  UNIQUE ("contest_id", "user_id")
);

CREATE INDEX ON "contest_members" ("user_id");

ALTER TABLE "contest_problems" ADD FOREIGN KEY ("contest_id") REFERENCES "contests" ("id") ON DELETE CASCADE;
ALTER TABLE "contest_problems" ADD FOREIGN KEY ("problem_id") REFERENCES "problems" ("id") ON DELETE CASCADE;

ALTER TABLE "contest_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "contest_members" ADD FOREIGN KEY ("contest_id") REFERENCES "contests" ("id") ON DELETE CASCADE;

ALTER TABLE "solutions" ADD COLUMN "contest_id" int;
ALTER TABLE "solutions" ADD COLUMN "contest_problem_id" int;

ALTER TABLE "solutions" ADD FOREIGN KEY ("contest_id") REFERENCES "contests" ("id") ON DELETE CASCADE;
ALTER TABLE "solutions" ADD FOREIGN KEY ("contest_problem_id") REFERENCES "contest_problems" ("id") ON DELETE CASCADE;
